### PR TITLE
Add dipakbari4

### PR DESCRIPTION
**Pull request by dipakbari4**
Added dipakbari4 [Dipak Bari] to README.md

### CODE REVIEW

**Review by dipakbari4 — COMMENTED** [review]
Added dipakbari4 [Dipak Bari]

**Review by dipakbari4 — COMMENTED** [review]
I've reviewed this file to make sure everything is working.

**Review by dipakbari4 — COMMENTED** [review]
Merge this one

**Comment by AnkushSinghGandhi** [comment]
Congratulations your pull request is merged 🎈

**Pull request merged**
