### PR TITLE
Add adityaraj079

### PR DESCRIPTION
**Pull request by adityaraj079**
Hope so i will not do the same in HacketoberFest-2021

### CODE REVIEW

**Comment by hibharat** [comment]
Dear Aditya Raj,

Congratulations!! You have successfully made your pull request. But by mistake, you have written your name in the wrong place. Please rewrite it in A`s column.

Best Regards
Bharat

**Review by adityaraj079 — COMMENTED** [review]
Added my name to A

**Comment by AnkushSinghGandhi** [comment]
Don't remove my name brother 😊

**Comment by AnkushSinghGandhi** [comment]
Screenshot from 2021-09-14 17-44-05

**Comment by adityaraj079** [comment]
Oo ok got it will do it

**Comment by adityaraj079** [comment]
Hey, now i did it correctly i think 
Can you plz check and close this pull request.

**Comment by AnkushSinghGandhi** [comment]
Congratulations your pull request is merged 🎈🎈

**Pull request merged**
